---
title: "field_observations"
output: html_document
---

## Date: June 1, 2026
**Location:** Salamanca, Spain

* **[Workplace]:** My colleagues in the Chamber of Commerce all appeared to be mid to late career professionals. The absence of young professionals in my workplace could be attributable to the lack of young talent in the corporate sector or a unique occurrence in the office.
* **[Sentiment]:** My host brother (age 40) informed me that Salamanca's local economy is dominated by the service industry and that many of his friends (presumably mid-career aged professionals) work as waiters. The latter piece of information seems to be a result of their local economy and age (they were young professionals during the Eurozone crisis).  

## Date: June 3rd, 2025
**Location:** Salamanca, Spain

* **[Sentiment]:** During my conversation in the park today with a retired farmer, he commented that the EU's free trade agreement with MERCOSUR disadvantages the region's farmers and leads to urban flight. Given that most small farms in the region are familial enterprises, it seems that an increasingly non-competitive agricultural industry could lead to over-saturation in urban job markets, a result young adults discontinuing the family business and moving to large cities.
* **[Workplace]:** In my role at the Chamber of Commerce, I have noticed multiple young adults meet with my associates for help finding employment. Furthermore, one of my office's main functions is hosting workshops concerned with developing human capital in the youth population.

## Date: June 5th, 2026
**Location**: Salamanca, Spain

* **[Macro]:** Observed in the local news that over 100 small businesses in the province are searching for a new owner because their current one is new retirement age. This statistic suggests a dearth of mid-career professionals who are able to fill such roles, likely a result of labor market rigidity. Qualified professionals with the skill to serve as owners are in protected jobs elsewhere. Alternatively, those that could have filled the role never developed the necessary human capital to do so because of dual labor market dynamics.
* **[Personal]:** My work with DAGs, paired with lived experiences in Salamanca, has caused the framework with which I'll approach my regression model to change. I must control for unobserved cultural/historical confounders (influential in both GDP and labor market rigidity) to prove that labor market rigidity is a structural driver of youth unemployment. I must also control for GDP growth rate, as it could bias my results according to the business cycle and other macro-trends that influence cyclical unemployment. 

## Date: June 9th, 2026
**Location:** Salamanca, Spain
* **[Data/Work Comparison]:** After downloading and skimming EPL labor protection statistics today (for both regular and temporary contracts), I have gained a new understanding of Salamanca's local economy. The most recent data available for regular contracts in Spain sits around a 2 (historically closer to 2.5). This means that the labor protections for regular employees are quite high. Seeing that Spain's service industry workers are often proctected under permanent contracts and that Spain has a service dominant economy, many mid-career professionals occupy protected contracts in said industry. This sheds new light on the lack of youth working in restaurants and storefronts in Salamanca. Furthermore, I have made connections between the strictness on labor protections and other regional economic problems such as urban flight. In my internship at the Chamber of Commerce of Salamanca, I analyzed data from the Instituto Nacional de la Estadística, calculating that the population of people between the ages of 20 and 34 decreased 26.67 percent between 2012 and 2022. This mass exodus of such an integral base of the labor force has manifested itself in a more vulnerable economy (even when not including unemployment statistics). Thus, my investigations of labor protection strictness has not only given me a better understanding of unemployment dynamics, but broader regional trends as well. This interconectedness has grounded macroeconomics as a powerful tool of analysis for everyday phenomena and micro-dynamics.

## Date: June 12-13, 2026
**Location:** Gijón, Spain
During my weekend in Gijón, I noticed many differences between its economy and Salamanca's. Gijón seems to have greater diversity of industry, as opposed to Salamanca's service/tourism dependent economy. Gijón possesses much more modern architecture (with various construction projects underway), many shipyards, and a busy port with lots of infrastructure. The city's cultural artifacts reflect this industrial history, with murals of shipyard workers on the Playa de Poniente's strip and the Museo del Ferrocarril de Asturias nearby. Apart from Gijón's more advanced industrial sector, its service sector seems to differ from Salamanca's as well. Those who man the restaurants of Gijón (appearing to be in their 20s or 30s) are consistently younger than their counterparts in Salamanca (many in their late 40s and 50s). These important differences in local economies merely 330km (by road) apart demonstrate the duality crux at the heart of the phenomenon I am studying, and justify my choice to implement country-level fixed effects. Addressing the duality crux, the presence of young workers in Gijón's service sector helps to explain why the youth unemployment rate skyrockets during times of recession. A large share of positions in the service industry fall under temporary contracts which are the first to be terminated in times of recession because the strict protections on laying off employee under regular contracts make doing so very costly and legally restrictive. This leads young laborers on temporary contracts to take the brunt of the ramifications resulting from recession-time downsizing. Furthermore, youth in Spain across various sectors usually work under temporary contracts, elucidating why youth unemployment spikes so aggressively in economic downturns. As for country level fixed effects, speaking from solely qualitative observation and economic intuition, the baseline levels of youth unemployment between Gijón and Salamanca likely differ because their economies are not identical in structure (industry vs. service) nor is the composition of certain sectors (the demographic gap demonstrated through service sector). Thus, if baseline rates of youth unemployment can vary for cities that share the same national law, culture, and history, the baseline rate for other countries sharing none of those traits should vary even more drastically. In order to truly clarify the causal relationship between strict labor market protections (particularly those that establish dual labor markets) and youth unemployment in economic downturns, the markedly different levels of baseline youth unemployment in the countries featured in my analysis must be accounted for (this is what variable a_i does). Once accounted for, my model can discern how the fluctuations in a single country's youth unemployment rate in the face of continent-wide macroeconomic shocks (such as the Eurozone crisis) are affected by the strictness of their national labor protection laws. In short, the use of country-level fixed effects ensures that my model can clarify the value of B1 (representing how much the magnitude of recession-prompted fluctuations in youth unemployment changes for each one-unit increase in EPL strictness), and thereby the value of B1*D (amount a given country's EPL strictness increases its recession-prompted changes in youth unemployment).